[package]
authors = ["Ernestas Poskus <ernestas.poskus@gmail.com>"]
build = "build.rs"
description = """
Top Level domain static hash map, tld list is obtained from of iana.org
"""
documentation = "https://docs.rs/tld"
homepage = "https://github.com/ernestas-poskus/tld.rs"
license = "BSD-3-Clause"
name = "tld"
repository = "https://github.com/ernestas-poskus/tld.rs"
version = "2.38.0"

edition = "2021"
rust-version = "1.70"
readme = "README.md"
keywords = ["tld", "domain", "iana", "validation", "lookup"]
categories = ["network-programming", "web-programming", "data-structures"]

[dependencies]
phf = { version = "0.11", default-features = false }

[build-dependencies]
phf_codegen = "0.11"
